# Generated by Django 5.0.7 on 2025-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto_servico',
            field=models.ImageField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
