# Generated by Django 5.0.7 on 2025-01-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_servico_foto_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='foto_servico',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
