# Generated by Django 5.1.4 on 2025-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
